repos:
- repo: https://github.com/PyCQA/autoflake
  rev: v1.4
  hooks:
  - id: autoflake
    args: ["-i", "--remove-all"]
    
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      args: ["--profile", "black", "--line-length", "120"]

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    args: ["--line-length=120"]